name: disposables

packages:
  - packages/**

scripts:
  analyze:
    run: |
      flutter pub global run melos exec -c 1 --ignore="*example*" -- \
      flutter analyze --fatal-infos .
    description: |
      Format code all lints from analysis_options.yaml

  analyze:find_unused_files:
    run: |
      flutter pub global run melos exec -c 1 --ignore="*example*" -- \
      flutter pub run dart_code_metrics:metrics check-unused-files lib
    description: |
      Find all unused files

  format:
    run: |
      flutter pub global run melos exec -c 5 --ignore="*example*" -- \
      flutter format .
    description: |
      Format code

  format:check:
    run: |
      flutter pub global run melos exec -c 5 --ignore="*example*" -- \
      flutter format --set-exit-if-changed --dry-run .
    description: |
      Check is code properly formatted

  generate:build_runner:
    run: |
      flutter pub global run melos exec -c 1 --fail-fast --depends-on="build_runner" -- \
      "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Generate all code via build_runner tasks(moor, freezed, json, etc)

  test:unit:
    run: flutter pub global run melos exec -c 1 --fail-fast -- \
      flutter test
    description: Run Flutter tests for a specific package in this project.
    select-package:
      dir-exists: test

  clean:
    run: flutter pub global run melos exec -c 1 flutter clean
    description: Clear all packages

  pub:get:
    run: |
      flutter pub global run melos exec -c 1 --fail-fast -- \
      flutter pub get
    description: pub get for all packages

  pub:packages:upgrade:
    run: |
      flutter pub global run melos exec -c 1 --fail-fast -- \
      flutter packages upgrade
    description: |
      Update packages cache to update git dependencies.
      Don't forget to increase version number in updated packages

  pub:publish:dry-run:
    run: |
      flutter pub global run melos exec -c 5 --no-private -- \
            pub publish --dry-run
    description: |
      Dry-run publish packages to pub dev

  pub:publish:
    run: |
      flutter pub global run melos exec -c 5 --no-private -- \
            pub publish
    description: |
      Publish packages to pub dev