name: disposables
version: 0.0.1
description: Disposable is responsible for auto disposing resources.
homepage: https://github.com/mosamuhana
repository: https://github.com/mosamuhana/dart_disposables

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  flutter_lints: ^1.0.4
